# Define a configuração para rodar com imagens do Docker Hub
version: '2'
volumes:
  logs:
    driver: local
services:
  rabbit:
    extends:
      file: shared/compose/common.yml
      service: rabbit
  discovery:
    extends:
      file: shared/compose/common.yml
      service: discovery
  gateway:
    extends:
      file: shared/compose/common.yml
      service: gateway
    depends_on:
     - discovery
  ui:
    extends:
      file: shared/compose/common.yml
      service: ui
    depends_on:
     - gateway
  userauthentication:
    extends:
      file: shared/compose/common.yml
      service: userauthentication
    depends_on:
     - rabbit
     - discovery
