version: '2'
services:
  rabbit:
    container_name: rabbit
    image: rabbitmq:management
    ports:
     - "5672:5672"
     - "15672:15672"
  discovery:
    container_name: discovery
    image: discovery
    ports:
     - "8761:8761"
     - "47961:47961"
    environment:
     - JAVA_OPTS=-Xdebug, -Xrunjdwp:server=y,transport=dt_socket,address=47961,suspend=n
  gateway:
    container_name: gateway
    image: gateway
    ports:
     - "8765:8765"
     - "47965:47965"
    environment:
     - JAVA_OPTS=-Xdebug, -Xrunjdwp:server=y,transport=dt_socket,address=47965,suspend=n
  ui:
    container_name: ui
    image: plataforma-ui
    ports:
     - "8443:8443"