server:
  port: 8081

spring:
  application:
    name: services
  devtools:
    remote:
      secret: stfdigital  
  datasource:
    url: jdbc:h2:mem:services;MODE=Oracle;DB_CLOSE_DELAY=-1
    username: sa
    password: 
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none

eureka:  
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    preferIpAddress: true
    
flyway:
  validate-on-migrate: false
