# Define a configuração para rodar o recebimento
version: '2'
services:
  services:
    extends:
      file: compose/shared/common.yml
      service: services
    depends_on:
     - rabbit
     - discovery