# Extende a configuração para rodar os testes e2e.
# Deve ser rodado em combinação com shared/compose/docker-compose.e2e.base.yml
version: '2'
services:
  services:
    extends:
      file: shared/compose/common.yml
      service: services
    image: stfdigital-plataforma-services
    depends_on:
     - rabbit
     - discovery
