# Define a configuração para rodar esse contexto construído localmente
version: '2'
services:
  services:
    extends:
      file: shared/compose/common.yml
      service: services
    image: stfdigital-plataforma-services
    depends_on:
     - rabbit
     - discovery
